# Generated by Django 4.2.5 on 2023-10-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_church_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='past_services',
            field=models.TextField(default='none'),
        ),
    ]
