# Generated by Django 4.2.5 on 2023-10-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicitem',
            old_name='user',
            new_name='added_by',
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='past_performances',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
