# Generated by Django 4.2.5 on 2023-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('music', '0002_rename_user_musicitem_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicitem',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='music', to='keywords.keyword'),
        ),
    ]
