# Generated by Django 4.2.5 on 2023-10-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicitem_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicitem',
            name='recording',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='sheet_music_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
