# Generated by Django 4.2.5 on 2023-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
        ('music', '0004_alter_musicitem_recording_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicitem',
            old_name='added_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='keywords',
            field=models.ManyToManyField(related_name='music', to='keywords.keyword'),
        ),
    ]
