# Generated by Django 4.2.5 on 2023-10-05 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0008_remove_musicitem_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicitem',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music', to=settings.AUTH_USER_MODEL),
        ),
    ]
