# Generated by Django 4.2.5 on 2023-10-05 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0009_musicitem_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicitem',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
