# Generated by Django 4.2.5 on 2023-10-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_musicitem_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
