# Generated by Django 4.2.5 on 2023-10-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
        ('music', '0012_musicitem_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicitem',
            name='related_readings',
        ),
        migrations.AddField(
            model_name='musicitem',
            name='related_readings',
            field=models.ManyToManyField(related_name='related_reading', to='readings.relatedreading'),
        ),
    ]
