# Generated by Django 4.2.5 on 2023-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
        ('keywords', '0003_remove_keyword_related_music_items'),
        ('music', '0013_remove_musicitem_related_readings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicitem',
            name='keywords',
            field=models.ManyToManyField(related_name='related_music', to='keywords.keyword'),
        ),
        migrations.AlterField(
            model_name='musicitem',
            name='related_readings',
            field=models.ManyToManyField(related_name='related_music', to='readings.relatedreading'),
        ),
    ]
