# Generated by Django 4.2.5 on 2023-10-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_alter_musicitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicitem',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='musicitem',
            name='recording',
        ),
        migrations.RemoveField(
            model_name='musicitem',
            name='sheet_music_url',
        ),
    ]
