# Generated by Django 4.2.5 on 2023-10-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_remove_musicitem_comments_remove_musicitem_recording_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musicitem',
            unique_together=set(),
        ),
    ]
