# Generated by Django 4.2.6 on 2023-10-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_alter_musicitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicitem',
            old_name='user',
            new_name='added_by',
        ),
    ]
