# Generated by Django 4.2.5 on 2023-10-05 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_of_service',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='service',
            name='type_of_service',
            field=models.CharField(default='sunday service', max_length=50),
        ),
    ]
