# Generated by Django 4.2.5 on 2023-10-05 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_service_date_of_service_service_type_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ManyToManyField(related_name='past_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
