# Generated by Django 4.2.5 on 2023-10-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_service_user_service_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='music_items',
            field=models.CharField(default='none'),
        ),
    ]
