# Generated by Django 4.2.5 on 2023-10-09 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_date_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_of_service',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
