# Generated by Django 4.2.5 on 2023-10-09 10:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0008_alter_service_date_of_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('date_of_service', 'type_of_service', 'user')},
        ),
    ]
