# Generated by Django 4.2.5 on 2023-10-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField()),
                ('chapter', models.PositiveIntegerField()),
                ('start_verse', models.PositiveIntegerField()),
                ('end_verse', models.PositiveIntegerField()),
                ('text', models.CharField()),
            ],
        ),
    ]
