# Generated by Django 4.2.5 on 2023-10-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_alter_relatedreading_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relatedreading',
            unique_together=set(),
        ),
    ]
