# Generated by Django 4.2.5 on 2023-10-09 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0020_alter_musicitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.musicitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
