# Generated by Django 4.2.5 on 2023-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_musicitem_keywords'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='related_music_items',
            field=models.ManyToManyField(related_name='related_keywords', to='music.musicitem'),
        ),
    ]
