# Generated by Django 4.2.5 on 2023-10-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keyword_related_music_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='related_music_items',
        ),
    ]
