# Generated by Django 4.2.6 on 2023-10-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_remove_keyword_related_music_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=50),
        ),
    ]
